services:
  back:
    image: tmp_back:local
    build:
      context: .
      dockerfile: back/Dockerfile
      target: dev
    command: sh -c "uv sync --frozen && uvicorn app.main:app --host 0.0.0.0 --reload --port 8000"
    volumes:
      - ./back/:/app/
      - back_venv:/app/.venv
      - uv_cache:/root/.cache/uv
    env_file:
      - secret/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - network_back
      - network_front
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - secret/.env
    ports:
      - "5431:5432"
    networks:
      - network_back
    environment:
      POSTGRES_USER: ${DB_USER:-tmp_user}
      POSTGRES_PASSWORD: ${DB_PASS:-tmp_password}
      POSTGRES_DB: ${DB_NAME:-tmp_local}
    restart: unless-stopped

  front:
    image: tmp_front:local
    build:
      context: .
      dockerfile: front/Dockerfile
      target: dev
    volumes:
      - ./front/:/app/
      - node_modules:/app/node_modules
    env_file:
      - secret/.env
    command: pnpm run dev --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - network_front
    restart: unless-stopped

volumes:
  db_data:
  node_modules:
  back_venv:
  uv_cache:

networks:
  network_back:
  network_front: