FROM node:22-alpine

# Set environment variables
ENV TZ=Asia/Tokyo
ENV NODE_ENV=production
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

# Use the correct timezone
RUN apk add --no-cache tzdata && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

RUN npm install -g pnpm

COPY ./front/package.json ./
COPY ./front/pnpm-lock.yaml ./
RUN pnpm install

COPY ./front ./

RUN pnpm run build

EXPOSE 3000
